### ISSUE TITLE
Stuck after first batch

### ISSUE THREAD

**Issue by bokova** [SGrondin/bottleneck#11]
Hi,
I've got an app that uses Bottleneck. It gets stuck after running the fist batch of requests. Could someone please help? Full description of the problem and app code is posted to [stackoverflow](http://stackoverflow.com/questions/35196265/why-does-this-bottleneck-ed-app-stall)

Thanks!

**Comment by SGrondin** [comment]
Welcome to Node.JS and concurrent (async) programming. The reason it's not working is that `callback()` is not always called, so it won't start new calls because it doesn't know your calls have finished.

Look inside of your `retryWrapper` function. There are four (!!!) `return` statements. If any of these statements are reached, `callback` will not be called. The problem is that you are mixing sync and async programming. Functions should either be 100% sync (return results with `return result`) or 100% async (return results with `callback(error, result)`). Not both at the same time!

If you absolutely want to finish an async function before the end, you need to call the callback and make sure **nothing else will be called after**. An easy way to do that is with `return callback()` because the `return` will stop anything else from executing inside the function. It's still an async function because the *control flow* is done with callbacks.

**Comment by SGrondin** [comment]
No response

**Comment by bokova** [comment]
Thank you, that worked for me!
Got a bunch of errors later on, but bottleneck not suspected.
(Sorry for posting late, only got to test yesternight actually due to workload :/)

**Comment by SGrondin** [comment]
Thanks for the feedback, good luck
