### ISSUE TITLE
How to get all queue counts in cluster?

### ISSUE THREAD

**Issue by jurajsipos** [SGrondin/bottleneck#111]
Hey guys,

is there any way how to get counts / no. queued jobs from all limiters in the cluster?
This would be super useful feature to monitor health of the cluster / know how much of jobs are currently distributed in local queues and depending on that regulate feeding of limiter.  

Many thanks and keep it up

**Comment by SGrondin** [comment]
Hi, this is a nice little feature that recently became possible to implement. I'm starting now and it will be done in a few hours, will you be able to try it and provide feedback?

**Comment by SGrondin** [comment]
Done in v2.16.0.

Use `limiter.clusterQueued()`. Please let me know if it works for you!

**Comment by jurajsipos** [comment]
Wow that was quick :), thanks a million!
Will try it first thing tomorrow and will let you know.

**Comment by SGrondin** [comment]
Yeah it was pretty quick because the required data was already being tracked correctly.

A few months ago I changed the scheduling logic to be deterministic and favor limiters that have not run a job recently, that way all limiters are guaranteed to get through their queues in a fair way. Here's the code that computes which limiter ('client') should run next: https://github.com/SGrondin/bottleneck/blob/d332f43db83a89a5ced235187d2ce1999bfd2fa6/src/redis/process_tick.lua#L112-L162

To write that code I had to start tracking which clients are 'active' (they've communicated with the Cluster in the last 10s) and their known number of queued jobs at any time (grab the initial number when they connect, then increase/decrease it as they process jobs).

So `.clusterQueued()` is just: https://github.com/SGrondin/bottleneck/blob/d332f43db83a89a5ced235187d2ce1999bfd2fa6/src/redis/queued.lua
1. Get all active clients
2. Get known queued for each
3. Sum it up

Plus the wiring, tests, etc.

**Comment by SGrondin** [comment]
Hi, this is definitely an error in Bottleneck itself, but all the tests are passing and I'm not able to trigger it at all. Could you paste your test that's failing and/or describe it? What are your settings?

**Comment by jurajsipos** [comment]
Hi,

after dropping redis container and clean install of node_modules it started working, so it was just weird state after upgrade maybe? 

Anyway, tested with 4 nodes cluster and `clusterQueued()` seems to be working as expected!

Many thanks @SGrondin!
Cheers

**Comment by SGrondin** [comment]
Glad to hear that! 🎉
