### ISSUE TITLE
Not seeing expected behaviour with reservoir refresh

### ISSUE THREAD

**Issue by robwold** [SGrondin/bottleneck#114]
I know other people have asked about this and it's turned out to not be an issue, so apologies if this turns out to be another instance of that. 
I tried writing a simple script before adding bottleneck to a production project and it's not behaving as I would expect. As you can see, I started by copying and pasting from the documentation before adding a simple async function I could provide with a variable load: 
```
const readline = require('readline');
const Bottleneck = require('bottleneck');

//limit to 5 requests every 10 s
const limiter = new Bottleneck({
    reservoir: 5, // initial value
    reservoirRefreshAmount: 5,
    reservoirRefreshInterval: 10 * 1000, // must be divisible by 250

    // also use maxConcurrent and/or minTime for safety
    maxConcurrent: 1,
    minTime: 10
});

const asyncDoubler = arg => Promise.resolve(arg * 2);
const wrappedDoubler = limiter.wrap(asyncDoubler) ;

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('Enter an array of numbers:\n', (answer) => {
  let array = JSON.parse(answer);
  console.time("rate-limited doubling");
  Promise.all(array.map(wrappedDoubler))
    .then(function(values) {
        console.log(values);
        console.timeEnd('rate-limited doubling');
        rl.close();
    });
});
```

If I provide `[1,2,3,4,5,6]` as input, I would expect it to take more than 10 seconds, but it takes anywhere between four and nine. Similarly, running it for an array with 11 entries took just under 16s, when I would expect it to take over 20s. Thanks in advance for any assistance.

**Comment by SGrondin** [comment]
Hi, this is an excellent question and it was fun to play with your script.

The reason you're seeing this behavior is that the refresh interval is independent from the time at which jobs are added to the limiter.

Assuming no `minTime` and no `maxConcurrent` for the sake of this example: If you happen to add 10 jobs just 1ms before the refresh is triggered, the first 5 will run immediately, then 1ms later it will refresh the reservoir value and that will make the last 5 also run right away. It will have run 10 jobs in just over 1ms no matter what your refresh interval was!

I took your example and hardcoded the array so that the jobs are always added right from the start instead of depending on how long a human takes to enter an array:
```js
const Bottleneck = require('bottleneck');

//limit to 5 requests every 10 s
const limiter = new Bottleneck({
    reservoir: 5, // initial value
    reservoirRefreshAmount: 5,
    reservoirRefreshInterval: 10 * 1000, // must be divisible by 250

    // also use maxConcurrent and/or minTime for safety
    maxConcurrent: 1,
    minTime: 10
});

const asyncDoubler = arg => Promise.resolve(arg * 2);
const wrappedDoubler = limiter.wrap(asyncDoubler);

const array = [1,2,3,4,5,6];
// const array = [1,2,3,4,5,6,7,8,9,10,11];

console.time("rate-limited doubling");

Promise.all(array.map(wrappedDoubler))
.then(function(values) {
    console.log(values);
    console.timeEnd('rate-limited doubling');
});
```
Try it out, it consistently runs in 10.1 seconds with 6 elements, and in 20.2s with 11 elements.

You can also visualize what is happening by adding a little bit of logging to your jobs:
```js
const t0 = Date.now();
const asyncDoubler = arg => {
    console.log(Date.now() - t0, arg);
    return Promise.resolve(arg * 2);
};
const wrappedDoubler = limiter.wrap(asyncDoubler);
```
This is the output I get with 6 elements:
```
8 1
15 2
26 3
35 4
45 5
10105 6
[ 2, 4, 6, 8, 10, 12 ]
rate-limited doubling: 10110.832ms
```
Back to your original script, with this improved logging, I get something like this:
```
Enter an array of numbers:
[1,2,3,4,5,6]
3592 1
3601 2
3612 3
3622 4
3631 5
10100 6
[ 2, 4, 6, 8, 10, 12 ]
rate-limited doubling: 6520.782ms
```
You can see that it took me 3592ms to type the array by hand. It says it took 6520ms to double the array, but if you moved the `console.time()` line to be right above the `rl.question()` line, then you'd get 10.1s as expected. The limiter starts its refresh interval when it's created, it doesn't wait for you to finish typing.

I hope that helps! Refresh intervals are tricky and `minTime` is enough for 95% of users, so that's why it took me over a year from the time this feature was suggested to adding it. It took me a long time to find the interface that would be the least confusing and least surprising. I consider "confusing documentation" to be a bug. You're probably not the first person to make this mistake, so is there anything you'd change to the Readme to help avoid this misunderstanding?

Thank you!

**Comment by robwold** [comment]
Thanks for your detailed reply, it clears things up completely. 

As for exactly how the misunderstanding arose: I think that when I read

> Sometimes, a quota resets on an interval

 I had in mind a use case for an API such as this one: https://locationiq.com/pricing
There you see that there are different rate limits at different levels of granularity, i.e. the rate limit over a minute is not simply that over a second scaled up by 60, and similarly for other time intervals. I was thinking that this feature could be used to enforce these 'coarser-grained' limits. (And I think it could still be used for that, but only with careful thought about the interplay with `minTime`.) It seems that the real point of the feature is

> refresh intervals should be only used to execute jobs in bursts

Where you don't need a hard guarantee on the time between bursts, but need them not to exceed a certain frequency on average over time. 

This behaviour is perfectly reasonable now I understand it properly, but if you did decide to add anything to the documentation I'd be inclined to use this example:

> If you happen to add 10 jobs just 1ms before the refresh is triggered, the first 5 will run immediately, then 1ms later it will refresh the reservoir value and that will make the last 5 also run right away. It will have run 10 jobs in just over 1ms no matter what your refresh interval was!

in the context of explaining the intended usage of the feature to space out batches of requests.

**Comment by SGrondin** [comment]
> There you see that there are different rate limits at different levels of granularity, i.e. the rate limit over a minute is not simply that over a second scaled up by 60, and similarly for other time intervals

I'm starting to realize that this might be the core of most misuses of Bottleneck. The way to handle it is to do something similar to what I wrote for the Octokit library: https://github.com/octokit/plugin-throttling.js/blob/769c1f26dd8c3c86b2e74a21d9d3be44aab16114/lib/wrap-request.js#L19-L29

Some requests are writes and need a `minTime: 1000` and some requests trigger notifications and need a `minTime: 3000`. At lines 21 and 26, I `await` an empty job (`noop`) to make the limiters wait the appropriate time. The actual job is executed at line 29 inside a limiter with `maxConcurrent: 1`.

What I'm going to do is, in the Readme, sum up what Refresh Intervals are for instead of jumping into examples and instead give examples of how to support multiple overlapping rate limits: by creating multiple limiters or using `chain()`.

Limiters are simple and small by design, to support complex use cases it's encouraged to create many of them and connect them together to solve a larger problem.

**Comment by SGrondin** [comment]
I've updated the Refresh Intervals documentation and moved it out of the Quick Start. Thanks for your input, it was helpful.
