### ISSUE TITLE
Redis CPU usage climbs as clients accumlate

### ISSUE THREAD

**Issue by avermeil** [SGrondin/bottleneck#115]
Hi there!

This is a follow up to https://github.com/SGrondin/bottleneck/issues/112 .

I'm experiencing a slowdown in my Bottleneck cluster. My Redis server's CPU has been climbing:

![image](https://user-images.githubusercontent.com/1063061/53182203-eca26680-35f0-11e9-9df4-08a172010bbe.png)

Looking at the slowlog, it looks like one of the lua scripts is to blame:

![image](https://user-images.githubusercontent.com/1063061/53182265-0e9be900-35f1-11e9-8f74-f97cdf87ce4e.png)

And indeed, I've got a whole lot of stale clients in my cluster (17k at this time):

![image](https://user-images.githubusercontent.com/1063061/53182405-5589de80-35f1-11e9-8e78-f136c1a7cf09.png)

All of the `*_client_*` keys have this same huge number of clients.

My clients are restarted quite frequently (roughly one restart per minute overall), and I don't get a chance to do any cleanup (stopping Bottleneck, closing Redis connections, etc). Back-of-the-napkin calculations suggest that each restart causes Bottleneck to keep a reference to a dead client.

I see that there's a `client_last_seen` key -- would it be possible to automatically delete clients that haven't been seen after some timeout?

Thanks for your help!

**Comment by SGrondin** [comment]
>Back-of-the-napkin calculations suggest that each restart causes Bottleneck to keep a reference to a dead client.

Indeed, it currently doesn't delete them since a reference to a client is so small. That avoids having to write extra logic to handle the case where a disconnected client reconnects after it has been deleted.

Your use case is more extreme, and the CPU usage rise is worse than I anticipated, so I'll add the logic to support it within the next few days.

By the way, this is the only "shortcut" that Bottleneck takes. Everything else is self-cleaning.

**Comment by avermeil** [comment]
Brilliant, thank you!

**Comment by SGrondin** [comment]
Fixed in https://github.com/SGrondin/bottleneck/releases/tag/v2.17.0

For the first time in a long time, I had to draw sequence and dependency diagrams on paper to make sure all possible race conditions are handled and covered by unit tests. All combinations and orderings of events should now converge to a state that leaves zero extraneous data in Redis *as long as all jobs have an `expiration`.*

Making these changes also allowed me to optimize the algorithm that selects which client should have priority when a cluster is running at maximum concurrency. On top of fixing the core slowdown, those optimizations should bring the base CPU usage even lower than before. It added a certain amount of complexity to the code, but it's absolutely worth it.

Please update me and lemme know how it behaves over time 😄

**Comment by avermeil** [comment]
Great! I'll deploy this new version and keep you up to date :)

**Comment by SGrondin** [comment]
I just realized that your extreme case (long expirations, short lived clients) might not lead to as smooth of a load distribution in v2.17 as the previous version. Nothing to be alarmed about since I doubt you'll be able to notice it anyway, but I'll release v2.17.1 later today.

**Comment by SGrondin** [comment]
2.17.1 is (finally) released. Enjoy!

**Comment by avermeil** [comment]
Thanks :)

Things have been running great since 2.17.0 -- no slowdown to be seen at all yet.

The Redis CPU usage on 2.17.0 is around 2x higher than the previous baseline, but shows no sign of increasing, which is fine by me.

We'll see how 2.17.1 behaves!

**Comment by avermeil** [comment]
Bottleneck has been running very well for us since 2.17.1.
Thanks for the great work :)

**Comment by SGrondin** [comment]
Woohoo! 🎉 Thanks for letting me know
