### ISSUE TITLE
How to save / load the limiter objects' status?

### ISSUE THREAD

**Issue by giacecco** [SGrondin/bottleneck#30]
Hi All,
Imagine I wanted to write a *command line script* in Node that needs to be rate-limited across multiple executions, e.g. a Twitter API client. I call it once, the limiter takes note of it, the script terminates. Then I call it again, the limiter *is aware* of the previous call, checks the limiting etc.

How do I manage this need with this library? E.g. can I "serialize" in some way the status of the library's objects, so that I can save them and re-load them back every time I run the script? I wouldn't want to use any backend component, as in the choice of Redis for [classdojo/rolling-rate-limiter](https://github.com/classdojo/rolling-rate-limiter), but would be happy with something simpler and slower, such as file system or environment variables. 

Thanks.

**Comment by SGrondin** [comment]
Hi, something you could do is keep the node process alive and your calls would spawn [child processes](https://nodejs.org/api/child_process.html).

However, I like the idea of being able to serialize the state and restore it at a later time. Stay tuned, I'll implement it soon.

**Comment by SGrondin** [comment]
Hi @giacecco, I've started looking into this and designing what the feature would look like. I would appreciate your input and opinion.

The first thing to realize is that the only things that can be serialized (and re-loaded) are the timings (how long until the next job can be launched?) and the ["reservoir"](https://github.com/SGrondin/bottleneck#changereservoir-incrementreservoir). Everything else, including how many jobs are currently running cannot be serialized, because they need information about functions and jobs that are running. For example, it's impossible to serialize `number of jobs running: 3` because the instance that loads that serialized state will never know when those 3 jobs terminate and so it'll forever think there are -at least- 3 jobs running.

Is it still useful if only those 2 features are serializable/loadable? It feels to me that simply *explaining* all the limitations of the feature would be confusing. If you think there's value to this feature, and that it can be well explained in the docs, then I would be open to implementing it.

**Comment by giacecco** [comment]
Probably I've used the "serialize" term inappropriately, trying to give you a solution instead of describing the problem. 

Describing the problem is simple, and it is to be able to throttle the same resource between different processes. In addition to that, I would like not to force the user to install anything but the Nodejs application itself (differently than - for example - what happens for classdojo/rolling-rate-limiter that requires Redis). 

Intuitively, some communication between the processes needs to take place, and I imagined that serialisation could be used to save the status of *bottleneck* to disk for other processes to read and behave accordingly. This is clearly a bad solution, because then you may have processes competing in writing the thing :-( What then? 

Perhaps each process could run like a "small server" locally, attempting to detect other processes running as peer and sharing the same resource, and then negotiating what happens?

**Comment by TheGame2500** [comment]
@SGrondin any updates on this?

**Comment by SGrondin** [comment]
Not really, @giacecco 's suggestion would introduce all sorts of complexity due to concurrent write accesses and Bottleneck also has to work in the browser. @TheGame2500 I've kept this issue open because I'm still open to adding something similar to what has been suggested so far, but I'd need a solid example of a realistic use case.

**Comment by TheGame2500** [comment]
@SGrondin @giacecco I'll tell you how I've done it. Kind of hacky since I'm not used to forking packages and I just edited `bottleneck/lib/Bottleneck.js` and  `bottleneck/lib/Cluster.js` but let's not focus on that aspect for now. Essentially I changed Bottleneck.js to take another two params, a `name` and a `redisURL`, and Cluster to pass `key` as `name` to the Bottleneck instance.

If Bottlenecks gets a `redisURL` it connects to redis runs `GET ${name}` and if it finds a value it assigns it to `self._nbRunning`, it also assigns itself an ID, which is just a UUID. It then opens another connection to redis and subscribes to the `name` channel, where it expects to gets messages in the form of 
```json
{
            from: QUEUE_ID,
            val: 1 or -1,
}
``` 
JSON serialised objects. After parsing them, if the `from` property is not equal to it's own ID, it adds `val` to `self._nbRunning`.

Finally, whenever _nbRunning is incremented or decremented, the Bottleneck instance sends `SET ${self.name} ${self._nbRunning}` to redis, and then sets a ttl of 10 minutes on the key to avoid leaking Redis memory, and also publishes a message on channel ${self.name} in the form of
```
{
            from: ${self._id},
            val: 1 or -1,
}
```
to update other potential queues listening to the channel that `_nbRunning` increased/decreased.

@SGrondin regarding running in the browser, not sure how to handle that, since this would make the package depend on some redis driver.

**Comment by SGrondin** [comment]
@TheGame2500 what you did is perfect for your use case. I think what I'll do is add events for `incrementNbRunning`, `decrementNbRunning` and all the other state changes you need to track to support all of Bottleneck's features (like reservoir, blocking, etc). Then you'll be able to put your Redis calls in those event listeners. It keeps Bottleneck generic, so someone could implement state saving using a datastore other than Redis if they want, and it'll keep working in the browser.

So by default it'd keep track of its state by itself as it currently does, but you'd be able to do it yourself by providing handlers for all those events.

**Comment by TheGame2500** [comment]
@SGrondin great! Sounds good, and better then my datastore gnostic version! Happy to have helped you with defining the use case. You might want to hint people in the docs to what the increment/decrement events could be used for as it doesn't feel quite obvious. @giacecco hope my use case helps you figure it out if you still need this.

**Comment by SGrondin** [comment]
I've come to the conclusion that the idea I suggested on October 3rd is simply not going to work. Individual clients need to be able to pass multiple arguments to a datastore, use them to mutate multiple values and then return other values, **all in a single atomic transaction or else race conditions occur**.

This work is not trivial to get right, so I don't want to rely on the end users to figure it out on their own. That work is also platform-specific, and I don't want to implement it for Redis, then again for Postgresql, and so on. I'll be implementing it once and I've decided on Redis.

In v2, creating a limiter is done by calling `new Bottleneck(obj)`, where `obj` is an object of arguments. One of those arguments will be the datastore to use, either `local` or `redis`.

Another argument will be an object of {name:  function}. That allows users to then submit/schedule jobs by their name instead of passing a function. When Redis is chosen as datastore, the limiter will only accept jobs by name, because the only way to get all of Bottleneck's functionalities to work in a distributed cluster, is by making it *possible for a job to be completed on a different client than the one it was submitted from*. This is why job all arguments, when using Redis, need to be serializable.

I'm almost done with v2.0, except for this fairly large feature. Any help with updating the documentation and the Typescript type definitions would be very appreciated and would speed it up.

**Comment by TheGame2500** [comment]
@SGrondin can we please have the possibility to select Redis db number (aka an argument to be passed to the SELECT redis command) ? Shouldn’t be hard to implement and would be a neat feature for keeping it neat and prevent potential conflicts with other clients over namespaces (although they should be fairly avoidable)

**Comment by TheGame2500** [comment]
@SGrondin my schedule doesn’t allow active coding on this, but if you have any hurdles you feel you need help with, I have some experience with building atomic transactions for queuing purposes in node (I accidentally built that for another microservice than the one above since I didn’t think to check whether a thing like bottleneck exists or not) and would be happy to offer my advice

**Comment by SGrondin** [comment]
Yes, selecting the DB number is a must. I'll let you know if I need help, but I've [done this before](https://github.com/newque/newque/blob/dee73e2cb7be8700847f9e5cf900731cc20b1b8c/src/persistence/redis/scripts/pull.lua) :)

**Comment by SGrondin** [comment]
@TheGame2500 @weeco

Version 2 is currently available for testing! 😄 

https://github.com/SGrondin/bottleneck/tree/version-2

Please give it a try, it includes Clustering, job weights and more. Your feedback is essential before I can confidently publish it to NPM.

**Comment by TheGame2500** [comment]
@SGrondin I'll be giving this a spin somewhere between Christmas and New Year's Eve. Really excited about it.

**Comment by SGrondin** [comment]
Version 2 has been released, please give it a try. Your feedback is welcome and appreciated!

To answer the original question:

You can rate limit your command line script across executions by using the Clustering feature. The limiter state will be stored in Redis. Clients (or scripts in your case) can come and go, multiple clients can be running simultaneously and Bottleneck will guarantee all those clients are correctly rate limited.
