### ISSUE TITLE
stopAll() indefinite nbRunning

### ISSUE THREAD

**Issue by chrisblossom** [SGrondin/bottleneck#31]
I am using limiting promises using ``limiter.schedule()``. When running ``limiter.stopAll()`` the queue is cleared, but whatever was running is never cleared and seems to just disappear. I am using ``limiter.nbRunning()`` to verify.

Am I doing something wrong or is this intended?

**Comment by SGrondin** [comment]
All queued up and scheduled jobs are cleared.

For the running jobs:
- If `rejectOnDrop` is `true`: (that's an option passed when instantiating the limiter), then your running jobs will be rejected with a failed promise. **But the job itself keeps running, because it's impossible to cancel function execution in JavaScript**. When that job terminates, Bottleneck will ignore the result, since it's already completed those jobs with a failed promise.
- If `rejectOnDrop` is false: the running jobs are simply ignored.

**Comment by SGrondin** [comment]
All queued up and scheduled jobs are always cleared.

For the running jobs, there are 2 settings that matter:
1. `interrupt`: `stopAll()` argument
2. `rejectOnDrop`: argument passed when creating the limiter
- If `interrupt` is false: The running jobs are ignored. They will complete successfully or fail on their own.
- If `interrupt` is `true` and  `rejectOnDrop` is `true`: The running jobs will be rejected immediately with a failed promise. **But the job itself keeps running, because it's impossible to cancel function execution in JavaScript**. When that job terminates, Bottleneck will ignore the result, since it has already completed those jobs with a failed promise.
- If `interrupt` is `true` and `rejectOnDrop` is false: the result of the running jobs (success or failure) will not be passed to the caller once they complete. Those promises are simply left hanging.

I'm adding all of that information to the README, I hope it answered your questions.

**Comment by chrisblossom** [comment]
Thank you for the detailed explanation.

I setup an example repo with all possible combinations of interrupt and rejectOnDrop to show what I am seeing: 
https://github.com/chrisblossom/bottleneck-example

I am trying to clear the queue and letting whatever is running finish running as it normally would.

**Comment by SGrondin** [comment]
Thank you, this is great, I'll have a look as soon as I can.

**Comment by SGrondin** [comment]
Hmm, something sticks out right away: you have the wrong number of arguments in your example.

[Here you have 4 arguments](https://github.com/chrisblossom/bottleneck-example/blob/30a3ba3212495edd69646e149d8672536c3730b3/index.js#L6-L9) and it's clear that you intended for the boolean to be `rejectOnDrop`'s setting.

The arguments are, in order:
- `maxConcurrent` (default `0`)
- `minTime` (default `0`)
- `highWater` (default `-1`)
- `strategy` (default `Bottleneck.strategy.LEAK`)
- `rejectOnDrop` (default `false`)

You can use `null` instead of `undefined` to skip an argument (and use the default).

Let me know if that fixes it, and if not I'll look it right away, I just came back from a trip.

**Comment by chrisblossom** [comment]
Good catch! I just tried it with the correct amount of arguments and the issue is still there.

**Comment by SGrondin** [comment]
Closing this since it won't be an issue in v2, [currently in beta](https://github.com/SGrondin/bottleneck/tree/version-2).
