### ISSUE TITLE
Add redis support for nodejs cluster support

### ISSUE THREAD

**Issue by ChadMC** [SGrondin/bottleneck#5]
It would be great if redis could be supported for handling multiple nodejs processes (cluster support). For example, if I'm running 4 nodejs instances with a load balancer in front, the bottleneck instance may not work as expected. Let's say there is a large number of hits coming into the site, and you need to ensure that the bottleneck limiter only executes 1 concurrent request at a time every 200ms. With a nodejs cluster, there will be 4 bottleneck limiter instances, each acting independently. So if the load balancer is spreading the load, you might be getting 4 concurrent requests running, instead of the expected 1 concurrent request. With redis support, they could all communication with each other and ensure that only 1 concurrent request is running at one time. I'm using the bottleneck cluster feature for all my work, so it would need to work with that as well. I hope this is explained well enough. Let me know if you need any more details.

**Comment by SGrondin** [comment]
Perfect explanation. I'd say Bottleneck is working as expected, because in its current state it is not expected to scale across multiple processes. However, adding multiprocess support using redis has been on the roadmap for a while.

I can't commit to it this week, but I plan to have it done at some point in the following 2 weeks.

Thanks for the issue and for using the library.

**Comment by SGrondin** [comment]
I've started looking into implementing this, but I'm running into roadblocks.

Basically, Bottleneck was designed to run in a single Node.js process. Trying to distribute it means that some Redis values need locks and there other tricky things to get right (if we don't want to end up in a deadlock if a process goes down, for example).

The main problem, though, is that there are actions that get executed when state changes. It's easy to do in a single process, we just call the function. But it breaks down when the code to call lives in a different process.

For example, when a job completes, the number of current jobs is decremented by 1 and Bottleneck will see if it can launch a new job. What happens if multiple instances are sharing the same state through Redis? The instance that just completed a job might not have any new jobs to launch in its local queue. Then how does it tell an instance elsewhere to run a job? It may not be able to open a socket to it and even if it could, then things get really nasty. What to do if the socket has issues? If there's a firewall, etc? The instances could communicate through Redis, but that causes other problems. Bottleneck is built in a way that it doesn't have a setInterval constantly checking to see if something needs to be done. It's always able to tell and schedule its tasks intelligently ahead of time. But now, each instance would need an Interval to check Redis (every 10ms? Less? That's insane, way too much load! But anything less and things won't happen at the time we want them to) and see if they need to do something. You can see where this is going. It's just madness.

A distributed rate-limiting system *can* be built and many probably already exist. However, it's not a simple task and after analyzing the situation carefully, I can safely say that it's beyond the scope of Bottleneck. Virtually no code could be reused, it's a totally different project.

If you want to solve your problem in a quick and dirty way, I suggest having a node.js process serve as a load balancer. That process would use Bottleneck to rate-limit and it would send messages to the other processes to tell them what work they need to do.

**Comment by SGrondin** [comment]
No response.
