### ISSUE TITLE
Question: Is it possible to get a batch of rate limited promises?

### ISSUE THREAD

**Issue by dcworldwide** [SGrondin/bottleneck#58]
I'm wondering if bottleneck is suitable for the following use case.

I have an high throughput API endpoint that receives requests from various sources. I'm using bottleneck.group to rate limit requests per source. Bottleneck does a great job of this.

In doing so, I realise there is a optimisation opportunity. Instead of processing each group request individually, I'd like to process a batch of requests per group. So if the rate limit was 1 request per 10 seconds, in the new design it would be any request that was queued within that 10 second unit.

Is that something I could achieve with bottleneck? Apologies if it's way out of scope for this library.

**Comment by SGrondin** [comment]
There isn't right now, but I love the idea. Bottleneck has a sibling project called [Newque](https://github.com/newque/newque) that's way more ambitious, way more powerful, but I'm taking a break from it at the moment. Many ideas and features of Bottleneck came from Newque and vice versa. What you're describing is called "Batching" in Newque and porting it to Bottleneck has been at the back of my mind for a few months.

Since you've expressed interest, I'm putting it at the top of the roadmap. Fixing bugs always takes priority over new features and I don't want to commit to any deadline, but I think it's something you can expect to see be added to Bottleneck before May.

If you want to get an idea of what it'll look like, search for "batch" on the Newque Readme and/or take a look at the [code](https://github.com/newque/newque/blob/master/src/persistence/batcher.ml).

**Comment by dcworldwide** [comment]
Oh nice. That's very interesting work. 

I'll keep watching how your work evolves. In the interim I've put together a quick solution https://stackoverflow.com/questions/49449900/batch-a-stream-of-requests-into-promises-grouped-by-time-interval/49460194#49460194. I'm not sure if it's very scalable though.

**Comment by SGrondin** [comment]
It took several months to improve Clustering to the point I could work on other features, but Batching is finally live! Upgrade to v2.12.0 to use it.

Another reason it took so long is I wasn't sure how to integrate it into limiters/groups/clustering/etc, so at the moment it's a totally separate feature. I fully expect that most users will use Batching and then add that batch as a job to a limiter. It might become more integrated if users request it.

The docs are [here](https://github.com/SGrondin/bottleneck#batching).

It's a small feature and the optimized source code is under [50 lines](https://github.com/SGrondin/bottleneck/blob/09b4b82a151634ea3bab4962d31488a1cf1804b9/src/Batcher.coffee)!

@dcworldwide even if you don't have a use case for it right now I'd still like to hear your thoughts on it. Enjoy!

**Comment by dcworldwide** [comment]
That is some excellent work @SGrondin 

I'm keen to switch over my implementation and run with yours. If I have any feedback from my testing will share :)
