### ISSUE TITLE
Support for redis sentinel

### ISSUE THREAD

**Issue by vinodjoseph91** [SGrondin/bottleneck#62]
Does bottleneck support **redis sentinel** for clustering. 
@SGrondin Any idea of supporting it ?

**Comment by SGrondin** [comment]
Bottleneck uses the https://github.com/NodeRedis/node_redis driver. NodeRedis does not appear to be compatible with Sentinel.

**Comment by SGrondin** [comment]
v2.8.0 adds support for ioredis, Redis Cluster and Redis Sentinel

- To use [ioredis](https://github.com/luin/ioredis) instead of Node Redis, pass the following option to Bottleneck: `{ datastore: "ioredis" }`. ioredis supports Redis Cluster and Redis Sentinel
- To use Redis Cluster, pass the following options to Bottleneck: `{ datastore: "redis", clusterNodes: [nodes] }`. See the [ioredis cluster](https://github.com/luin/ioredis#cluster) docs and the Bottleneck docs for more information
