### ISSUE TITLE
Executing vs Running

### ISSUE THREAD

**Issue by goldiloxio** [SGrondin/bottleneck#69]
I have a question and a potential issue about the fundaments of this library. 

I need to make sure that the API calls my app makes to third party applications doesn't exceed 3 every second. I thought `Bottleneck` would have been the solution but this is what I'm seeing:

Instead of executing 3 requests every second, `Bottleneck` runs 3 requests every second, executing only 1 every second. I can see this on a API service I built to test the behavior. It always receives 1 API call per second and never more.

I'm probably missing something here and I can use some help trying to figure this out.

Thank you.

**Comment by SGrondin** [comment]
I see the issue.

>executing only 1 every second

This is because you're asking Bottleneck to make sure the **start** of request 2 is at least `1000`ms after the **start** of request 1. Do this instead:

```js
const limiter = new Bottleneck({
  minTime: 333
});
```

And if you think there's a chance that some requests might take longer than `333`ms and you want to prevent that, then also add `maxConcurrent: 1` so Bottleneck won't let more than 1 run at a time.

**Comment by goldiloxio** [comment]
Now I understand better what `maxConcurrent` is for, thank you very much!

**Comment by SGrondin** [comment]
Thanks for the feedback, I've improved the README.
