### ISSUE TITLE
will priority be introduced to bottleneck?

### ISSUE THREAD

**Issue by mike442144** [SGrondin/bottleneck#7]
As title, I have a problem in my project, I have to use priority queue like which in [pool](https://github.com/coopernurse/node-pool). Is it possible to add priority to bottleneck ?

**Comment by SGrondin** [comment]
Maybe. I had ideas to add `submitNow` and `scheduleNow`, those 2 calls would add requests to the beginning of the queue instead of the end. Would that work for you?

**Comment by mike442144** [comment]
@SGrondin I've discussed with my colleagues, we have to use multi-level priorities to handle our tasks, so we are going to add priority queue if possible and commit PR then.

**Comment by SGrondin** [comment]
@mike442144 that is good news! If you could describe exactly how you envision the priorities I'd be happy to write the code. I have extremely high quality and style requirements for this project because the logic can get very complicated.

Would priority be a numerical value? Or any numerical value between 1 and 10? How many different priority levels? 3? 10? Are they always the same or do they change per limiter? Etc.

**Comment by mike442144** [comment]
@SGrondin We have used it for a long time, so that we have to add priority feature. As you said, priority should be a numerical value and the range could set when init. say 1 to 10 or 1 to 100, so we have 10 or 100 levels. Yep, they change for each limiter. I think that is same to [pool](https://github.com/coopernurse/node-pool)

**Comment by SGrondin** [comment]
I think it would be much cleaner and more performant if the number of levels were always the same and not configurable. Is that okay with your use case?

**Comment by mike442144** [comment]
@SGrondin Sure, it also make sense. Actually, 10 levels would be enough now.

**Comment by SGrondin** [comment]
I've started working on this feature. I'll let you know when I have a "beta" version for you to try.

**Comment by SGrondin** [comment]
There's a beta version you can try. In your `package.json`:

```json
  "dependencies": {
    "bottleneck":"git://github.com/SGrondin/bottleneck.git#priorities"
  }
```
Priorities go from `0` to `9`. `0` is the most important, `9` is the least important.

New functions are:
`submitPriority(priority, task, arg1, arg2, argN, cb)`:
Same as `submit`, but it takes an extra argument at the beginning. Jobs added with `submit` have a priority of `5`.

`schedulePriority(priority, task, arg1, arg2, argN)`:
Same as `schedule`, but it takes an extra argument at the beginning. Jobs added with `schedule` have a priority of `5`.

There will be something like `nbJobs(priority)` but it's not final yet.

Strategies are a little bit different because of the priorities. This is not final yet.

`LEAK`:
If a job is added when at the `highWater` limit, the oldest job with the lowest priority (lowest is 9) will be dropped. If all the current jobs have a higher priority than the new job, the new job is not added.

`OVERFLOW`:
If a job is added when at the `highWater` limit, the new job is not added, even if its priority is higher than some of the jobs in the queue.

`OVERFLOW_PRIORITY`:
Works like `LEAK` except that it will not drop a job with the same priority as the new job, it will drop the new job instead.

`BLOCK` is unchanged.

**Comment by mike442144** [comment]
That's cool, thanks a lot. I'll try later, and I notice that you link the issue to @darrenqc who is my colleague and he wrote the priority version by himself because we have to use it in our projects as soon as possible. We'll add more tests both in our version and your version to add to product.

**Comment by SGrondin** [comment]
Thank you, as soon as you've tested it I'll release it.

**Comment by SGrondin** [comment]
I just updated the `priorities` branch with an upgrade that I think will also fix #6 . Please let me know if you see a difference.

**Comment by SGrondin** [comment]
Hi @mike442144 I'm waiting for a reply from you before releasing 0.10.

**Comment by SGrondin** [comment]
I released 0.10.0. Please comment here if you're having any issues with it.

**Comment by mike442144** [comment]
@SGrondin I'm so sorry that I'm so busy with our projects this year, it's great to see your release, and now I'm trying to introduce into our production environment. I'll also comment here if I have any questions, really thanks you very much.

**Comment by SGrondin** [comment]
No problem @mike442144
