### ISSUE TITLE
Issue with _sanitizePriority(priority);

### ISSUE THREAD

**Issue by albertreed** [SGrondin/bottleneck#8]
Hello!

I was having a hard time getting priorities to work and discovered that priority = this._sanitizePriority(priority); seems to be changing the value of a validly passed priority inside of submitPriority() (which in my application is being called from schedulePriority).

Adding some logging so the function reads like this:

      console.log("TEMP_AJR args[0] in submit = " + arguments[0]);

      priority = arguments[0], task = arguments[1], args = 4 <= arguments.length ? slice.call(arguments, 2, j = arguments.length - 1) : (j = 2, []), cb = arguments[j++];

      console.log("TEMP_AJR pre-sanitize in submit = " + priority);

      priority = this._sanitizePriority(priority);

      console.log("TEMP_AJR sp in submit = " + priority);

logged this:
TEMP_AJR args[0] in submit = 6
TEMP_AJR pre-sanitize in submit = 6
TEMP_AJR sp in submit = 5

I'm a very inexperienced javascript programmer so I expect there's something wrong with how I'm using the library, but maybe there's some actual issue so I figured I'd pass on the note.

Hope this helps!

-Al

**Comment by SGrondin** [comment]
*Very* nice catch. It's 2 minor subtle issues that combined together caused the problem to happen.

- `schedulePriority` does not need to call `_sanitizePriority` because it doesn't use the priority, it only passes it to `submitPriority`.
- `Array.prototype.call` will create and flatten an array on the fly, there's no need to use `Array.prototype.call.concat`. `.call.concat` needs an array in the first argument for certain types, such as `null` and when the first argument is a number, it will create a prototype number such as `[Number: 6]` in your case.

Then that fake number is passed to `_sanitizePriority` a second time and now the comparison fails, so it defaults to the `MIDDLE_PRIORITY`, which is `5`.

I'm releasing `1.10.1` right now to fix it.

**Comment by SGrondin** [comment]
Released and fixed. You can see the fix [here](https://github.com/SGrondin/bottleneck/commit/8d1c30ebfd850ab1e70f5bd515e1af0515e59ba0) if you're curious. Thank you very much for your excellent debugging and for reporting the issue quickly.

**Comment by albertreed** [comment]
Happy to help! Thanks for the useful lib!

**Comment by SGrondin** [comment]
You're welcome! Feel free to comment here if you have any issues or even just questions about how to use it or how it works.
