### ISSUE TITLE
Writing schedule with async await syntax

### ISSUE THREAD

**Issue by jpike88** [SGrondin/bottleneck#80]
Is this:
```
limiter.schedule(fn)
.then((result) => { /* ... */ } )
.catch((error) => {
  if (error instanceof Bottleneck.prototype.BottleneckError) {
    /* ... */
  }
})
```

The same as this?
```
try {
 await limiter.schedule(fn)
} catch (error) {
  if (error instanceof Bottleneck.prototype.BottleneckError) {
    /* ... */
  }
}
```

I just want the function to complete successfully, so if I can write it all in that syntax that would be nice. Just want to know if that is not recommended etc

**Comment by SGrondin** [comment]
Almost, this is the exact same thing:
```js
try {
 const result = await limiter.schedule(fn)
} catch (error) {
  if (error instanceof Bottleneck.prototype.BottleneckError) {
    /* ... */
  }
}
```

Async/Await syntax uses Promises under the hood. You can use `await` on any function returning a Promise, and you can use `.then()` on any `async` function, this is just a part of JavaScript, it's not special to Bottleneck.

One thing that's nice about async/await is that it makes it really easy to see where all your failures go (the catch block). In Promise code, your synchronous exceptions might go to a different place than your rejected Promises. That's why I personally prefer writing code using async/await.

**Comment by SGrondin** [comment]
Please let me know if you have other questions.
