### ISSUE TITLE
Feature Request: allow multiple groups to share Redis connections

### ISSUE THREAD

**Issue by colinskow** [SGrondin/bottleneck#86]
Redis hosting plans which allow large numbers of connections tend to be quite expensive. My app is hitting dozens of API endpoints each with their own throttling scheme.

Is it technically feasible to allow groups with different `minTime` or `maxConcurrent` to share the same connections? This would save money on resources.

BeeQueue allows each group to share the same primary connection, and creates additional connections on-demand only when needed...

> `Note that this [Redis config] can also be a node_redis RedisClient instance, in which case Bee-Queue will issue normal commands over it. It will duplicate() the client for blocking commands and PubSub subscriptions, if enabled.

Related: #84

**Comment by SGrondin** [comment]
Not at the moment, but simple connection sharing should be released within the next 2-3 weeks.

**Comment by SGrondin** [comment]
I've completed the functionality and tests for this feature, it will be released in v2.11.0 in a few days.

The solution I came up with is more flexible than BeeQueue's. You'll be able to either:
- Pass a raw redis client and let Bottleneck create a new pubsub connection for every group and standalone limiter (same behavior as BeeQueue).
or
- Reuse the same client+pubsub pair across all your groups and limiters, which will guarantee that never more than 2 connections are open.

**Comment by colinskow** [comment]
@SGrondin docs look perfect. Thank you so much for your responsiveness. This will help a lot in keeping my bills down as I scale!

As for my use case, I'm doing web scraping for price monitoring of e-commerce sites.

I have a worker which tracks which URLs are due to be scraped and schedules them in BeeQueue at a random time in a window and limits the overall concurrency so as not to overload the worker.

I then have a bank of proxies and a load balancing algorithm which chooses a proxy balancing requests to each domain evenly across the proxies. Each proxy then has a master limiter in Bottleneck to prevent it from becoming overloaded. Each proxy-domain pair then has a Bottleneck limiter (chained to the master limiter) to reduce the chances of that proxy getting IP banned, and the settings can be customized to each domain.

So far I'm still in development on one worker getting the bugs worked out, but will soon scale to multiple workers.

**Comment by SGrondin** [comment]
[v2.11.0 has been released](https://github.com/SGrondin/bottleneck/releases/tag/v2.11.0)

**Comment by SGrondin** [comment]
That's a really cool use case, @colinskow . I hope Bottleneck is meeting your expectations. If something is missing feel free to open another issue. Deciding how to expose a feature to users is always harder than developing it. I had already begun thinking about manual connections so that's why this was so quick.

-----
I'd love to hear your thoughts on this @colinskow @gsmtamil @edwardupton @TheGame2500

I've been thinking about expanding Bottleneck into BeeQueue's territory since I began work on the Cluster feature a year ago. At the moment, I believe most Cluster users rely on some other library like BeeQueue or they just use their main SQL database as the queue. The `publish()` method I added recently was a first step in integrating this functionality into Bottleneck itself and it can be used to get around the current Clustering limitations.

The problem with adding this functionality is how to integrate it into the current library. Something like `new Bottleneck.Task()`? After using [Sidekiq](https://sidekiq.org/) professionally for a few years, I have a whole new level of expectation for a background processing system. I view it as a related but distinct problem from what Bottleneck does. The reason I'm even considering this is because of the limitations when using Clustering: priorities are almost useless, counts and most events are local only, etc. It's hard to explain in the docs what is Cluster-wide and what is local.

So should a task processing system be integrated at all? Or should those hypothetical tasks have to call limiters manually? If it's manual then what even is the point of adding this to Bottleneck?

**Comment by TheGame2500** [comment]
@SGrondin I have no experience whatsoever with BeeQueue though I have heard of it. Would you mind explaining how the newly integrated Task would be different to a queued job right now and potentially offer a use case  ?

**Comment by SGrondin** [comment]
Suppose this code is running on a Cluster of 10 computers:
```js
const limiter1 = new Bottleneck({
  shareQueue: true,
  id: "process-spreadsheet",
  maxConcurrent: 2,
  minTime: 500,
  clientOptions: {}
});

limiter1.on("run", (arg1, arg2) => {
  // process job
});

limiter1.schedule({ priority: 1, expiration: 10*1000 }, arg1, arg2)
.then((result) => { /* ... */ });
```
In this example, any Nodejs process in the Cluster can add jobs. Any of those handling the `"run"` event might have to execute the job.

This is profoundly different from the current system. Not only can jobs be executed on a different process, it also means the arguments and results need to be serialized and passed over the network. What it gives us is priorities and counts that work cluster-wide and queues that are stored entirely inside Redis, so queued jobs aren't lost when a client disconnects.

It's an entirely different paradigm and I'd like to know if there's any interest. It would be a huge effort. Something like `shareQueue: true` is probably not a good idea because it means all of a limiter's features now need to work in this totally different paradigm. Maybe this needs to be a different library or maybe Bottleneck needs to have built-in integrations with something like BeeQueue.

Would any of this be useful?

**Comment by colinskow** [comment]
It would certainly be nice to handle all scheduling and limiting with one API. But the queue and limiter do serve distinctly different roles, so I'm trying to wrap my head around how they would work together.

Currently I use BeeQueue to schedule jobs in approximate time windows, and the limiter to make sure resources don't get overloaded. Right now I have a function that handles queue jobs which are ready to run, and that then waits for the appropriate limiters (proxy, domain etc.) before executing the actual task.

It seems to work the way it's set up, but I'm always open to ideas for making it better!

**Comment by SGrondin** [comment]
Thanks for the feedback.

> But the queue and limiter do serve distinctly different roles, so I'm trying to wrap my head around how they would work together.

The more I think about it, the more I think this is exactly right. Limiters do have a queue of their own, but trying to build a proper queue out of a limiter seems like the wrong way around.

I'll keep thinking about this and I might reach out to the BeeQueue maintainers to suggest integrating Bottleneck into BeeQueue as an optional setting.
