### ISSUE TITLE
Question: How to executing multiple jobs concurrently?

### ISSUE THREAD

**Issue by pedromss** [SGrondin/bottleneck#87]
I'm trying to experiment with this lib and the goal is to execute jobs concurrently every X seconds.

I thought the following example would achieve that:
```javascript
const Bottleneck = require('bottleneck')
const now = Date.now();

const limiter = new Bottleneck({
  maxConcurrent: 2,
  minTime: 2000
});
const f1 = () => {
  const secDiff = ((Date.now() - now) / 1000).toFixed();
  return Promise.resolve(`${secDiff}s`);
}

limiter.schedule(f1).then(console.log)
limiter.schedule(f1).then(console.log)
limiter.schedule(f1).then(console.log)
limiter.schedule(f1).then(console.log)
```

Expected output:
```text
0s
0s
2s
2s
```

Actual output:
```
0s
2s
4s
6s
```

What am I missing here? Am I miss interpreting the `maxConcurrent` parameter?

**Comment by skreis** [comment]
I'm working through understanding the documentation as well and as far as I can tell, your configuration states that there is a 2 second interval between each task, with a max concurrency which would allow 2 long-running tasks to be running in parallel.

`maxConcurrent` says:
> How many jobs can be executing at the same time. 

`minTime` says:
> How long to wait after launching a job before launching another one.

I don't think you're seeing that because of the nature of the task you're running.
I'm also not sure that this particular library is the correct one for your goal – maybe you want something more like this? http://caolan.github.io/async/docs.html#parallelLimit

**Comment by pedromss** [comment]
@skreis Thanks for the clarification :)

**Comment by SGrondin** [comment]
@pedromss @skreis 

It was late when I replied last night and I forgot to show you exactly how you can achieve what you want. By the way I don't think `parallelLimit` can do it either. Make sure you're using the latest version of Bottleneck (2.11.1):

```js
const Bottleneck = require('bottleneck')
const now = Date.now();

const limiter = new Bottleneck({
  reservoir: 2,
  reservoirRefreshAmount: 2,
  reservoirRefreshInterval: 2000
});
const f1 = () => {
  const secDiff = ((Date.now() - now) / 1000).toFixed();
  return Promise.resolve(`${secDiff}s`);
}

limiter.schedule(f1).then(console.log);
limiter.schedule(f1).then(console.log);
limiter.schedule(f1).then(console.log);
limiter.schedule(f1).then(console.log);

setTimeout(() => {
  console.log('Done!');
}, 2500);
```
Output:
```
0s
0s
2s
2s
Done!
```
`reservoir` is a counter decremented every time a job is run. Once it reaches 0, nothing can run until it is no more 0. Its initial value is set to 2. Every `reservoirRefreshInterval` ms (2000), the limiter's reservoir is reset to `reservoirRefreshAmount` (2).

We need that `setTimeout` because in your example there is nothing to prevent the Node process from exiting once the limiter starts waiting for the reservoir to be incremented. In a real world scenario there'd be an http server, database connections, etc, to keep the Node process alive.
